_target_: muonly.models.TrackerTrackSelectionModel

net: ${net}

in_keys:
  tracker_track: tracker_track
  tracker_track_data_mask: tracker_track_data_mask
  dt_segment: dt_segment
  dt_segment_data_mask: dt_segment_data_mask
  csc_segment: csc_segment
  csc_segment_data_mask: csc_segment_data_mask
  gem_segment: gem_segment # GE0
  gem_segment_data_mask: gem_segment_data_mask
  rpc_hit: rpc_hit
  rpc_hit_data_mask: rpc_hit_data_mask
  gem_hit: gem_hit # GE11, GE21
  gem_hit_data_mask: gem_hit_data_mask

optim_config: ${optim}

pos_weight: null
