tracker_track: [
    'px', 'py', 'pz',
    'vx', 'vy', 'vz',
    'charge',
]

dt_segment: [
    'pos_x', 'pos_y', 'pos_z',
    'dir_x', 'dir_y', 'dir_z',
]

csc_segment: [
    'pos_x', 'pos_y', 'pos_z',
    'dir_x', 'dir_y', 'dir_z',
]

gem_segment: [
    'pos_x', 'pos_y', 'pos_z',
    'dir_x', 'dir_y', 'dir_z',
]

rpc_hit: [
    'pos_x', 'pos_y', 'pos_z',
]

gem_hit: [
    'pos_x', 'pos_y', 'pos_z',
]


# the preprocessing parameters
preprocessing:
  tracker_track_log: # signeld log1p
    # signed_log1p is applied to momentum and vertex position, not to charge
    index: [
      0, 1, 2, # px, py, pz
      3, 4, 5, # vx, vy, vz
    ]

    # after log
    mean: [
      0, 0, 0,
      0, 0, 0,
      0
    ]
    std: [
      0.4277, 0.4274, 1.5307,
      0.0611, 0.0612, 1.4953,
      1.0
    ]

    # FIXME:
    offset: [
      0, 0, 0,
      0, 0, 0,
      0,
    ]

    scale: [
      8.072, 8.769, 10.882,
      1.257, 2.938, 4.735,
      1.0,
    ]

  # Segments
  # [pos_x, pos_y, pos_z, dir_x, dir_y, dir_z]
  dt_segment:
    offset: [
      0, 0, 0, # pos_x, pos_y, pos_z
      0, 0, 0, # dir_x, dir_y, dir_z
    ]
    scale: [
      770.354, 720.480, 649.957,
      1, 1, 1,
    ]

  csc_segment:
    offset: [
      0, 0, 0,
      0, 0, 0
    ]
    scale: [
      679.842, 685.146, 1037.740,
      1, 1, 1,
    ]

  gem_segment:
    offset: [
      0, 0, 0,
      0, 0, 0
    ]
    scale: [
      142.471, 144.120, 538.790,
      1, 1, 1
    ]

  # Hits
  # [pos_x, pos_y, pos_z]
  rpc_hit:
    offset: [
      0, 0, 0
    ]
    scale: [
      754.477, 704.550, 1066.155,
    ]

  gem_hit:
    offset: [
      0, 0, 0
    ]
    scale: [
      311.673, 312.111, 799.551,
    ]
