_target_: muonly.data.DataModule

dataset: muonly.data.TrackerTrackSelectionDataset

root: ${paths.data_dir}

train_file: train.h5
val_file: val.h5
test_file: val.h5
predict_file: val.h5

tracker_track_feature_list: ${data.tracker_track.features}
dt_segment_feature_list: ${data.dt_segment.features}
csc_segment_feature_list: ${data.csc_segment.features}
gem_segment_feature_list: ${data.gem_segment.features}
rpc_hit_feature_list: ${data.rpc_hit.features}
gem_hit_feature_list: ${data.gem_hit.features}

preprocessing:
  tracker_track: ${data.tracker_track.preprocessing}
  dt_segment: ${data.dt_segment.preprocessing}
  csc_segment: ${data.csc_segment.preprocessing}
  gem_segment: ${data.gem_segment.preprocessing}
  rpc_hit: ${data.rpc_hit.preprocessing}
  gem_hit: ${data.gem_hit.preprocessing}

target_key: ${exp.target_key}

batch_size: 128
eval_batch_size: 128
train_sampler: null

num_workers: 0
pin_memory: false

train_max_events: null
val_max_events: null
test_max_events: null
predict_max_events: null
