# @package _global_

defaults:
  - exp: tracker-track-selection
  - paths: default

  - datamodule: default
  - feature_set: pqv

  - augmentation: none
  - preprocessing: tracker-track-log_minmax
  - model: latent_attention
  - postprocessing: default

  - criterion: bce

  - optimizer: adamw
  - lr_scheduler: plateau

  - metric: default

  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim

  - run: default

  - torch: default
  - hydra: default
  - debug: null

  - _self_

feature_set:
  rpc_hit: null # RPC out

preprocessing:
  partial_tolerant: true

model:
  rpc_hit_dim: null

  in_keys:
    tracker_track_prep: tracker_track
    tracker_track_data_mask: tracker_track_data_mask
    dt_segment_prep: dt_segment
    dt_segment_data_mask: dt_segment_data_mask
    csc_segment_prep: csc_segment
    csc_segment_data_mask: csc_segment_data_mask
    gem_segment_prep: gem_segment
    gem_segment_data_mask: gem_segment_data_mask
    gem_hit_prep: gem_hit
    gem_hit_data_mask: gem_hit_data_mask


exp:
  name: tracker-track-selection_wo-rpc
