# @package _global_

defaults:
  - torch: default
  - hydra: default
  - exp: tracker_track_selection
  - paths: default
  - feature_set: pqv
  - datamodule: default
  - augmentation: none
  - preprocessing: tracker-track-log_minmax
  - model: latent_attention
  - postprocessing: default
  - criterion: bce
  - optimizer: adamw
  - lr_scheduler: plateau
  - metric: default
  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim
  - run: default
  - _self_
  - debug: null
