# @package _global_


defaults:
  - torch: default
  - hydra: default
  - exp: tracker_track_selection
  - paths: default
  - feature_set: pqv
  - datamodule: default
  - augmentation: none
  - preprocessing: tracker-track-log_minmax
  - model: latent_attention
  - postprocessing: default
  - criterion: bce
  - optimizer: adamw
  - lr_scheduler: plateau
  - metric: default
  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim
  - run: default
  - _self_
  - debug: null

feature_set:
  gem_segment : null # no GEM segments in Run 3

preprocessing:
  partial_tolerant: true

model:
  gem_segment_dim: null

  in_keys:
    tracker_track_prep: tracker_track
    tracker_track_data_mask: tracker_track_data_mask
    dt_segment_prep: dt_segment
    dt_segment_data_mask: dt_segment_data_mask
    csc_segment_prep: csc_segment
    csc_segment_data_mask: csc_segment_data_mask
    rpc_hit_prep: rpc_hit
    rpc_hit_data_mask: rpc_hit_data_mask
    gem_hit_prep: gem_hit
    gem_hit_data_mask: gem_hit_data_mask

exp:
  name: tracker-track-selection_run3
  target_key: is_tracker_muon
  pos_weight: 30.0

paths:
  data_dir: /hdfs/ml/muonly/data/CMSSW_14_0_21_patch1/mu2024pu/
