# @package _global_

defaults:
  - torch: default
  - hydra: default
  - paths: default
  - run: default

  - data: pqv
  - datamodule: default

  - model: tts
  - net: latent_attention

  - optim: default

  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim

  - _self_

  - debug: null

exp:
  name: tracker_track_selection_run3
  target_dim: 1
  target_key: track_is_trk_muon

data:
  gem_segment: null

model:
  pos_weight: 30.0

  in_keys:
    - tracker_track
    - tracker_track_data_mask
    - dt_segment
    - dt_segment_data_mask
    - csc_segment
    - csc_segment_data_mask
    - rpc_hit
    - rpc_hit_data_mask
    - gem_hit # GE11, GE21
    - gem_hit_data_mask

paths:
  data_dir: /hdfs/ml/muonly/data/CMSSW_14_0_21_patch1/mu2024pu/
