root_dir: ${oc.env:PROJECT_ROOT}
log_dir: ${paths.root_dir}/logs/
run_dir: ${paths.log_dir}/${exp.name}/${run.name}
work_dir: ${hydra:runtime.cwd}

data_dir: /home/joshin/workspace-gate/DeepMuonReco/DeepMuonReco/data/mu2030pu/
